languageCode = "en-us"

baseURL             = "https://www.homeonrails.com/"
copyright           = "All rights reserved"
paginate            = 10
pluralizeListTitles = false
theme               = "hyde"
title               = "Home on Rails"
canonifyurls        = true
disqusshortname    = "homeonrails"

[permalinks]
  post = "/:year/:month/:slug/"

[Menus]
  main = [
      {Name = "About author", URL = "/about"},
      {Name = "Most popular posts", URL = "/most-popular-posts"},
      {Name = "Tags", URL = "/tags"},
  ]

[params]
  author                = "Anton Kaliaev"
  authorlocation        = ""
  authorwebsite         = "https://www.homeonrails.com"
  bio                   = "Software engineer, blogger, public speaker, traveler"
  cover                 = "images/cover.png"
  description           = "Success is not final, failure is not fatal: it is the courage to continue that counts. Winston Churchill"
  googleAnalyticsUserID = ""
  hideHUGOSupport       = false
  logo                  = "images/logo.png"
  hjsStyle              = "solarized-dark"
  githubName            = "melekes"
  twitterName           = "akaliaev"
  customHeaderPartial   = "header.include.html"
  themeColor            = "theme-base-0d"

[sitemap]
  ChangeFreq = ""
  Filename   = "sitemap.xml"
  Priority   = "-1"
